Repository Jguer/yay, pull requests merged in 2019-10, with the labels that each got.

#1049 FR #994: Implement proper diff display
  download.go
  install.go
Labels: Status: In Progress, Type: Feature Request

#1056 Add --searchby
  config.go
  depPool.go
  go.mod
  go.sum
  parser.go
  query.go
  vendor/github.com/Jguer/go-alpm/package.go
  vendor/github.com/Jguer/go-alpm/types.go
  vendor/github.com/mikkeloscar/aur/aur.go
  vendor/modules.txt
Labels: Status: In Progress, Type: Enhancement

#1053 Re-add --batchinstall and fix dep issues
  clean.go
  cmd.go
  config.go
  install.go
  parser.go
Labels: Status: In Progress, Type: Enhancement

#1067 Support AURDEST
  main.go
Labels: Status: Missing documentation

#1068 Move abs cloning to it's own directory
  config.go
  download.go
  parser.go
Labels: Status: Missing documentation
